"""
simulate.py — Stochastic synthetic-sequence generation from a fitted ARIMA model.

Added 2026-08-12 per supervisor instruction: the project's original validation
compared a single forecast to the single observed sequence that followed,
which he called meaningless for a stochastic model ("each forecast is
different... you cannot compare... you can only compare the parameters of
what you forecast to the parameters of your original data"). This module
generates an ENSEMBLE of independent synthetic realisations from the fitted
model; validation.py then compares the *distribution* of each realisation's
statistical properties to the historical record, not point values.

Each realisation is generated by recursively applying the fitted ARMA
recursion to fresh random innovations, with a burn-in period discarded so the
process reaches its stationary distribution before the retained window
starts, then integrating back through any differencing and the log transform.
"""

import numpy as np

from .model import ARIMA, integrate_forecasts
from .preprocess import inv_log_transform

BURN_IN = 200


def _simulate_w(model: ARIMA, n_periods: int, n_reps: int, rng, method: str) -> np.ndarray:
    """Simulate n_reps realisations of the (possibly differenced) log-scale
    series w, each of length n_periods, via the fitted ARMA recursion."""
    p, q = model.p, model.q
    phi, theta, c, sigma2 = model.phi, model.theta, model.c, model.sigma2
    total = BURN_IN + n_periods

    if method == "bootstrap":
        resid_pool = model.resid_
        if len(resid_pool) < 2:
            raise ValueError("Residual pool too small to bootstrap from.")

    sims = np.zeros((n_reps, total))
    for r in range(n_reps):
        if method == "gaussian":
            e = rng.normal(0.0, np.sqrt(sigma2), total)
        elif method == "bootstrap":
            e = rng.choice(resid_pool, size=total, replace=True)
        else:
            raise ValueError(f"Unknown innovation method {method!r}")

        w = np.zeros(total)
        for t in range(total):
            ar = np.dot(phi, w[t - p:t][::-1]) if p and t >= p else 0.0
            ma = np.dot(theta, e[t - q:t][::-1]) if q and t >= q else 0.0
            w[t] = c + ar + ma + e[t]
        sims[r] = w
    return sims[:, BURN_IN:]


def simulate_ensemble(model: ARIMA, y_hist: np.ndarray, n_periods: int,
                       n_reps: int = 500, method: str = "gaussian",
                       seed: int = None) -> np.ndarray:
    """
    Generate an ensemble of synthetic realisations on the natural (level)
    scale, continuing on from the end of y_hist.

    Parameters
    ----------
    model      : ARIMA already fitted (or built via ARIMA.from_params)
    y_hist     : log-scale history the differencing is anchored to (only the
                 tail is used, via integrate_forecasts, when d > 0)
    n_periods  : length of each synthetic realisation, in months
    n_reps     : number of independent realisations
    method     : "gaussian"  -- innovations drawn from N(0, sigma2), the
                                 model's own error-variance estimate
                 "bootstrap" -- innovations resampled (with replacement)
                                 from the model's in-sample residuals, which
                                 relaxes the Gaussian-innovation assumption
    seed       : RNG seed for reproducibility

    Returns
    -------
    ndarray of shape (n_reps, n_periods), natural units (back-transformed
    from the log scale).
    """
    rng = np.random.default_rng(seed)
    sims_w = _simulate_w(model, n_periods, n_reps, rng, method)

    if model.d > 0:
        y_hist = np.asarray(y_hist, dtype=float)
        sims_log = np.array([integrate_forecasts(y_hist, w, model.d) for w in sims_w])
    else:
        sims_log = sims_w

    return inv_log_transform(sims_log)


if __name__ == "__main__":
    from .preprocess import build_monthly_dataset, split_monthly
    from .calibrate import select_order

    df = build_monthly_dataset("discharge")
    train, valid = split_monthly(df)
    order, model, table, diff_info = select_order(train["log_value"].to_numpy())
    print(f"Selected order: {order}")

    ens = simulate_ensemble(model, train["log_value"].to_numpy(), len(valid),
                             n_reps=200, seed=42)
    print(f"Ensemble shape: {ens.shape}")
    print(f"Historical validation mean: {valid['value'].mean():.3f}")
    print(f"Synthetic ensemble mean (median across reps): {np.median(ens.mean(axis=1)):.3f}")
    print(f"Synthetic ensemble mean 90% envelope: "
          f"[{np.percentile(ens.mean(axis=1), 5):.3f}, {np.percentile(ens.mean(axis=1), 95):.3f}]")
